### ISSUE TITLE
🐛 YARRML with condition is not parsed correctly 

### ISSUE THREAD

**Issue by Mar-ai** [RMLio/matey#4]
I followed the example 105 on https://rml.io/yarrrml/spec/#conditions and created the YARRRML like so 

```yaml
prefixes:
  ex: "http://example.com/"

mappings:
  name:
    sources:
      - ['some.csv~csv']
    subjects: $(NAME)
    condition:
      function: equal
      parameters:
         - [valueParameter, $(IMPORTANTVALUE)]
         - [valueParameter2, "yes"]
    predicateobjects:
     - predicates: ex:isFriendsWith
       objects: $(FRIEND)
```

but when I put the generated rml-File through `morph_kgc.materialize`  I get the error `KeyError: 'object-map' `
