### ISSUE TITLE
Matey does not show mapper output as soon as a graphs key is added to the YARRRML input

### ISSUE THREAD

**Issue by mvanbrab** [RMLio/matey#6]
- If the graphs key is ommitted in the test input below, the output consists of RDF output and RML rules.
- If the graphs key is added, the output consists of RML rules only.

```yaml
prefixes:
  ex: http://www.example.com/
  e: http://myontology.com/
  dbo: http://dbpedia.org/ontology/
  grel: http://users.ugent.be/~bjdmeest/function/grel.ttl#
  schema: http://schema.org/
  
mappings:
  people:
    sources:
      - ['people.csv~csv']
    s: ex:$(id)
    # next key is the problem
    graphs: ex:Characters
    po:
      - [a, schema:Person]
      - [schema:givenName, $(firstname)]
      - [schema:familyName, $(lastname)]
```

people.csv:

```
id,firstname,lastname,debut episode,hair color
0,Natsu,Dragneel,1,pink
1,Gray,Fullbuster,2,dark blue
2,Gajeel,Redfox,21,black
3,Lucy,Heartfilia,1,blonde
4,Erza,Scarlet,4,scarlet
```
